# We have to import the necessary library
# We have to load the dataset
# We have to do some  Preprocess Step
# we have to draw some plot(boX plot, Bar plot, histogram,)
# Implementation of EDA

In [3]:
pip install matplotlib

Requirement already satisfied: matplotlib in /home/artic-rage/anaconda3/lib/python3.14/site-packages (3.11.0)
Requirement already satisfied: contourpy>=1.0.1 in /home/artic-rage/anaconda3/lib/python3.14/site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /home/artic-rage/anaconda3/lib/python3.14/site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /home/artic-rage/anaconda3/lib/python3.14/site-packages (from matplotlib) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /home/artic-rage/anaconda3/lib/python3.14/site-packages (from matplotlib) (1.4.9)
Requirement already satisfied: numpy>=1.25 in /home/artic-rage/anaconda3/lib/python3.14/site-packages (from matplotlib) (2.4.6)
Requirement already satisfied: packaging>=20.0 in /home/artic-rage/anaconda3/lib/python3.14/site-packages (from matplotlib) (26.0)
Requirement already satisfied: pillow>=9 in /home/artic-rage/anaconda3/lib/python3.14/site-packages (from matplotlib) (12.3.0)
Requirement already satisfied: pyparsing>=3 in /home/artic-rage/anaconda3/lib/python3.14/site-packages (from matplotlib) (3.2.5)
Requirement already satisfied: python-dateutil>=2.7 in /home/artic-rage/anaconda3/lib/python3.14/site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /home/artic-rage/anaconda3/lib/python3.14/site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('weather.csv')
df

            date  precipitation  temp_max  temp_min  wind  weather
0     2012-01-01            0.0      12.8       5.0   4.7  drizzle
1     2012-01-02           10.9      10.6       2.8   4.5     rain
2     2012-01-03            0.8      11.7       7.2   2.3     rain
3     2012-01-04           20.3      12.2       5.6   4.7     rain
4     2012-01-05            1.3       8.9       2.8   6.1     rain
...          ...            ...       ...       ...   ...      ...
1456  2015-12-27            8.6       4.4       1.7   2.9     rain
1457  2015-12-28            1.5       5.0       1.7   1.3     rain
1458  2015-12-29            0.0       7.2       0.6   2.6      fog
1459  2015-12-30            0.0       5.6      -1.0   3.4      sun
1460  2015-12-31            0.0       5.6      -2.1   3.5      sun

[1461 rows x 6 columns]

In [3]:
df.shape

(1461, 6)

In [4]:
df.columns

Index(['date', 'precipitation', 'temp_max', 'temp_min', 'wind', 'weather'], dtype='str')

In [6]:
df.describe(include = "object")

/tmp/ipykernel_14961/3591357663.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.describe(include = "object")

              date weather
count         1461    1461
unique        1461       5
top     2012-01-01    rain
freq             1     641

In [7]:
df.dtypes

date                 str
precipitation    float64
temp_max         float64
temp_min         float64
wind             float64
weather              str
dtype: object

In [10]:
df["date"] = pd.to_datetime(df["date"])

In [11]:
df.head()

        date  precipitation  temp_max  temp_min  wind  weather
0 2012-01-01            0.0      12.8       5.0   4.7  drizzle
1 2012-01-02           10.9      10.6       2.8   4.5     rain
2 2012-01-03            0.8      11.7       7.2   2.3     rain
3 2012-01-04           20.3      12.2       5.6   4.7     rain
4 2012-01-05            1.3       8.9       2.8   6.1     rain